version: "3.6"
services:
  webui:
    container_name: webui
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /var/www/webui-vuejs
    volumes:
      - .:/var/www/webui-vuejs
      - /var/www/webui-vuejs/node_modules
    environment:
      - npm_config_unsafe_perm=true
    ports:
      - 8080:8080
